Repository EGC-Serranito/serranito-hub, pull requests merged in 2024-11, with the labels that each got.

#55 ask - WI Bot integration - feature execution bot
  app/__init__.py
  app/modules/botintegration/repositories.py
  app/modules/botintegration/routes.py
  app/modules/botintegration/services.py
  app/modules/botintegration/templates/botintegration/index.html
  requirements.txt
Labels: hard, ask

#65 show - WI download all datasets - feature download all dataset
  app/modules/auth/repositories.py
  app/modules/auth/services.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/download/__init__.py
  app/modules/download/assets/scripts.js
  app/modules/download/forms.py
  app/modules/download/models.py
  app/modules/download/repositories.py
  app/modules/download/routes.py
  app/modules/download/seeders.py
  app/modules/download/services.py
  app/modules/download/templates/download/index.html
  app/modules/download/tests/__init__.py
  app/modules/download/tests/locustfile.py
  app/modules/download/tests/test_selenium.py
  app/modules/download/tests/test_unit.py
  app/modules/profile/repositories.py
  app/templates/base_template.html
Labels: show

#66 ship - WI download all datasets - feature update migration file
  migrations/versions/001.py
Labels: ship

#67 ship - WI download all datasets - feature download dataset by user email
  app/modules/download/routes.py
  app/modules/download/services.py
  app/modules/download/templates/download/index.html
Labels: ship

#69 show - WI Bot integration - feature cross module functionality
  app/__init__.py
  app/modules/botintegration/assets/messages.yaml
  app/modules/botintegration/features.py
  app/modules/botintegration/forms.py
  app/modules/botintegration/repositories.py
  app/modules/botintegration/services.py
  app/modules/botintegration/templates/botintegration/index.html
  app/modules/flamapy/routes.py
  app/modules/public/routes.py
Labels: hard, show, High Priority

#72 show - WI Improve UI - feature redesign interface
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/profile/templates/profile/edit.html
  app/modules/public/templates/public/index.html
  app/templates/base_template.html
Labels: show

#77 show - WI Improve UI - feature dark/light mode switch
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/signup_form.html
  app/modules/botintegration/templates/botintegration/index.html
  app/modules/dashboard/templates/dashboard/index.html
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/download/templates/download/index.html
  app/modules/explore/templates/explore/index.html
  app/modules/explore/tests/test_selenium.py
  app/modules/profile/templates/profile/edit.html
  app/modules/profile/templates/profile/summary.html
  app/modules/profile/templates/profile/view_profile.html
  app/modules/public/templates/public/index.html
  app/modules/team/templates/team/index.html
  app/static/css/app.css
  app/static/css/own.css
  app/templates/base_template.html
Labels: show
