Repository EGC-Serranito/serranito-hub, pull requests merged in 2024-12, with the labels that each got.

#88 show - Wi download all datasets - feature download all dataset
  app/modules/download/tests/test_selenium.py
  app/modules/download/tests/test_unit.py
Labels: ask

#98 show - Wi fakenodo - feature tests
  app/modules/fakenodo/tests/locustfile.py
  app/modules/fakenodo/tests/test_selenium.py
  app/modules/fakenodo/tests/test_unit.py
Labels: show

#96 show - WI Download all datasets - feature test all cases
  app/modules/download/tests/locustfile.py
Labels: show

#100 ask - WI UVL editor - feature uvl editing in backend Closes #79
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/update_dataset.html
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/zenodo/services.py
Labels: ask

#111 show - WI Improve UI - feature create tests
  app/modules/dashboard/tests/__init__.py
  app/modules/explore/tests/__init__.py
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_unit.py
Labels: show

#110 ask - WI Bot integration - feature test all functionalities
  app/modules/botintegration/assets/scripts.js
  app/modules/botintegration/features.py
  app/modules/botintegration/models.py
  app/modules/botintegration/repositories.py
  app/modules/botintegration/routes.py
  app/modules/botintegration/seeders.py
  app/modules/botintegration/services.py
  app/modules/botintegration/templates/botintegration/index.html
  app/modules/botintegration/tests/locustfile.py
  app/modules/botintegration/tests/test_features_unit.py
  app/modules/botintegration/tests/test_selenium.py
  app/modules/botintegration/tests/test_unit.py
  bot_configuration_click_error.png
  error_screenshot.png
  error_state.html
  error_state.png
  timeout_features-selection.png
Labels: ask

#117 show - WI New Test Cases/feature import data in external mysql database closes #115
  .env.local.example
  .github/workflows/populateRenderDev.yml
  .github/workflows/populateRenderProd.yml
  app/__init__.py
  core/managers/config_manager.py
  docker/images/Dockerfile.render
  rosemary/cli.py
  rosemary/commands/populate_dev_db.py
  scripts/special/updateLastLine.py
  uploads/user_1/dataset_1/file1.uvl
  uploads/user_1/dataset_1/file2.uvl
  uploads/user_1/dataset_1/file3.uvl
  uploads/user_1/dataset_3/file7.uvl
  uploads/user_1/dataset_3/file8.uvl
  uploads/user_1/dataset_3/file9.uvl
  uploads/user_2/dataset_2/file4.uvl
  uploads/user_2/dataset_2/file5.uvl
  uploads/user_2/dataset_2/file6.uvl
  uploads/user_2/dataset_4/file10.uvl
  uploads/user_2/dataset_4/file11.uvl
  uploads/user_2/dataset_4/file12.uvl
Labels: show, High Priority

#121 ship - New test cases/feature add selenium and locust tests closes #118
  app/modules/profile/tests/locustfile.py
  app/modules/profile/tests/test_selenium/test_edit_profile.py
  app/modules/profile/tests/test_selenium/test_view_my_profile.py
Labels: ship

#112 show - WI Dashboard - feature refactor methods
  app/modules/dashboard/services.py
  app/modules/dashboard/templates/dashboard/index.html
  app/modules/dashboard/tests/test_selenium.py
  app/modules/dashboard/tests/test_unit.py
Labels: show

#120 show - WI Bot integration - feature test all functionalities
  app/modules/botintegration/assets/messages.yaml
  app/modules/botintegration/features.py
  app/modules/flamapy/routes.py
Labels: show

#134 show - WI Dashboard - feature refactor all dashboard code Closes #94
  app/modules/dashboard/repositories.py
  app/modules/dashboard/routes.py
  app/modules/dashboard/services.py
  app/modules/dashboard/templates/dashboard/index.html
  app/modules/dashboard/tests/test_unit.py
Labels: show

#133 show - Wi sign up validation - feature add tests for the new functionality
  app/modules/auth/routes.py
  app/modules/auth/tests/test_integration.py
  app/modules/auth/tests/test_selenium_ide/test_signup_validation.py
  app/modules/auth/tests/test_unit.py
Labels: show

#140 ask-WI Upload analyse and repair uvl-feature uvl file validation and correction
  .gitignore
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/flamapy/models.py
  app/modules/flamapy/services.py
  app/modules/hubfile/assets/js/scripts.js
  app/modules/hubfile/assets/js/webpack.config.js
  app/modules/hubfile/assets/scripts.js
  app/modules/hubfile/routes.py
  package-lock.json
  package.json
  requirements.txt
Labels: ask

#148 show-WI Upload analyse and repair uvl-feature create tests
  app/modules/hubfile/tests/locustfile.py
  app/modules/hubfile/tests/test_uvl_selenium.py
Labels: show
